project_id = "rymlbukljujtvbyhuswg"

[functions.manage-users]
verify_jwt = false

[functions.seed-admin]
verify_jwt = false

[functions.backup-rekap-drive]
verify_jwt = false

[functions.check-drive-status]
verify_jwt = false
